name: "Podcast Generator"
author: "Ray Villalobos"
description: "Generates a feed for a podcast from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
inputs:
  email:
    description: The committer's email address
    required: true
    default: ""  # You can set this to an empty string or remove it
  name:
    description: The committer's name
    required: true
    default: ""  # You can set this to an empty string or remove it